# Generated by Django 5.2.11 on 2026-03-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("rating", models.FloatField(default=0.0)),
                ("description", models.TextField(max_length=500)),
            ],
        ),
    ]
