# Generated by Django 5.2.11 on 2026-03-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
